builds:
- goarch:
    - amd64
brews:
- github:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
- name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
